shield_enable: true
credential_provider: shield
credentials:
  shield:
    user: root
    pass: password
print: Hello!
allow_cli: true
_core:
  default_config_hash: yHBuI_J_kdrugm0JRNsxHODZ0qQyPzejI6r1ZPacK5Q
whitelist: ''
